/* =========================================================
   Portfolio content — edit this file to update your site.
   ========================================================= */

window.PORTFOLIO = {
  profile: {
    name: "Ashish Kumar Chaubey",

    role: "Full Stack Developer · Backend & AI Specialist",
    email: "sashishchaubey1234@gmail.com",
    phone: "+91-9076536204",

    photo: "./assets/profile-photo.jpg",

    links: {
      github: "https://github.com/AshishChaubey2003",
      linkedin: "https://www.linkedin.com/in/ashishchaubey2dec/",
      resume:"https://drive.google.com/file/d/120FebuFvrTjrejOLp1rIBCBpKEmnUEBN/view?usp=sharing",
    },
  },

  skills: [
    {
      category: "Languages",
      icon: "code",
      items: ["Python", "SQL", "JavaScript (ES6+)"],
    },
    {
      category: "Backend & API",
      icon: "server",
      items: [
        "Django",
        "Django REST Framework",
        "FastAPI",
        "REST API Design",
        "JWT",
        "OAuth2",
        "Swagger UI",
      ],
    },
    {
      category: "GenAI & LLMs",
      icon: "brain",
      items: [
        "LangChain",
        "LangGraph",
        "Groq API",
        "Llama 3 70B",
        "FAISS",
        "HuggingFace",
        "Google Gemini",
        "Pinecone",
        "RAG Pipelines",
        "Prompt Engineering",
      ],
    },
    {
      category: "Frontend",
      icon: "palette",
      items: [
        "React",
        "React Router",
        "Axios",
        "Leaflet.js",
        "HTML5",
        "CSS3",
        "Tailwind CSS",
        "Streamlit",
      ],
    },
    {
      category: "Databases",
      icon: "db",
      items: [
        "PostgreSQL",
        "MySQL",
        "SQLite",
        "Redis",
        "SQLAlchemy ORM",
        "Django ORM",
        "Schema Design",
      ],
    },
    {
      category: "Infra & DevOps",
      icon: "cloud",
      items: [
        "Apache Kafka",
        "Redis",
        "Celery",
        "Docker",
        "Docker Compose",
        "Nginx",
        "Gunicorn",
        "Prometheus",
        "Grafana",
        "n8n",
        "Render",
        "Vercel",
        "CI/CD",
      ],
    },
  ],

  projects: [
    {
      id: "travelx",
      name: "TravelX",
      subtitle: "Event-Driven AI Travel Booking Platform",
      period: "Jan 2025 — Apr 2025",
      stack: [
        "Django",
        "DRF",
        "PostgreSQL",
        "Redis",
        "Celery",
        "Kafka",
        "Razorpay",
        "React",
        "Docker",
        "Nginx",
        "Groq AI",
      ],
      highlights: [
        "Architected event-driven booking system using Kafka topics — decoupled booking, email, analytics & inventory services for independent horizontal scaling.",
        "Implemented multi-layer data integrity via select_for_update() + transaction.atomic() to prevent race conditions; Razorpay webhook verification with HMAC-SHA256 and idempotency keys.",
        "Configured Redis across 3 isolated DBs (cache/session/Celery broker) with TTL invalidation; integrated Leaflet.js maps and full Razorpay Checkout + webhook payment flow.",
        "Built React.js frontend with Axios API integration, dynamic map views via Leaflet.js, responsive HTML5/CSS3 layouts; JWT auth with OTP email verification and RBAC.",
      ],
      tags: ["Full Stack", "Backend", "AI"],
      accent: "cyan",
      links: {
        code: "https://github.com/AshishChaubey2003/TravelX",
        live: "#",
      },
    },
    {
      id: "ai-doc-intelligence",
      name: "AI-DOC-INTELLIGENCE",
      subtitle: "Enterprise Document Q&A with AI-Powered RAG Pipeline",
      period: "Mar 2025 — Present",
      stack: [
        "FastAPI",
        "React",
        "PostgreSQL",
        "Redis",
        "Groq LLaMA 3.3 70B",
        "Pinecone",
        "Docker",
        "Grafana",
        "Prometheus",
        "n8n",
      ],
      highlights: [
        "Built FastAPI backend with JWT authentication, document upload (PDF/DOCX/TXT/Images), and real-time AI Q&A using Groq LLaMA 3.3 70B (~500ms response time).",
        "Engineered RAG pipeline with Pinecone vector database for semantic search; PyPDF2 for PDF processing; Redis caching for 40% faster repeated queries.",
        "Integrated Grafana + Prometheus monitoring dashboard for real-time metrics; n8n workflow automation for document processing pipelines.",
        "Dockerized full stack architecture (Frontend, Backend, PostgreSQL, Redis, n8n, Grafana, Prometheus) — one-command deployment with 100% FREE tier ($0/month).",
      ],
      tags: ["AI", "Full Stack", "Backend"],
      accent: "violet",
      links: {
        code: "https://github.com/AshishChaubey2003/ai-doc-intelligence",
        live: "#",
      },
    },
    {
      id: "freshplate",
      name: "AI FreshPlate",
      subtitle: "AI-Powered Food Ordering & Food Rescue Platform",
      period: "Aug 2024 — Feb 2025",
      stack: [
        "Django",
        "DRF",
        "PostgreSQL",
        "JWT",
        "Google Gemini",
        "Docker",
        "React",
        "Render",
        "Vercel",
      ],
      highlights: [
        "Designed 10+ RESTful APIs with JWT auth and 3-tier RBAC (Admin, Customer, Donor); food donation module with 3-step approval workflow (submitted → verified → dispatched).",
        "Integrated Google Gemini AI chatbot for personalized food recommendations, menu assistance and real-time order support with custom prompt pipeline.",
        "Built React.js frontend consuming APIs via Axios with responsive HTML5/CSS3 UI; scalable PostgreSQL schema using Django ORM with optimized queries.",
        "Deployed on Render (backend) + Vercel (frontend) with GitHub Actions CI/CD enabling zero-downtime automated deployments on every push to main.",
      ],
      tags: ["Full Stack", "Backend", "AI"],
      accent: "emerald",
      links: {
        code: "https://github.com/AshishChaubey2003/Ai_Fresshplate",
        live: "https://ai-fresshplate.vercel.app/",
      },
    },
    {
      id: "ai-code-reviewer",
      name: "AI Code Reviewer",
      subtitle: "Agentic Code Review Tool with Self-Healing Loop",
      period: "Oct 2024 — Feb 2025",
      stack: [
        "LangGraph",
        "LangChain",
        "Groq API",
        "Llama 3 70B",
        "FAISS",
        "HuggingFace",
        "Streamlit",
      ],
      highlights: [
        "Engineered a 5-node LangGraph agentic state machine (analyze_bugs, auto_fix, security, quality, report) with conditional self-healing loop that rewrites buggy code and retries up to 3 iterations.",
        "Built RAG pipeline using FAISS vector store and HuggingFace all-MiniLM-L6-v2 embeddings; users upload custom PDF coding guidelines for context-aware personalized reviews.",
        "Deployed OWASP Top 10 security audit, PEP8 compliance and performance review as separate agent nodes with individual scoring (0–10); downloadable fix report and corrected .py file.",
        "CI/CD via GitHub Actions to Streamlit Cloud with automated testing; handles complex codebases with multi-file dependency analysis.",
      ],
      tags: ["AI"],
      accent: "violet",
      links: {
        code: "https://github.com/AshishChaubey2003",
        live: "https://aujd96shly6j3xw4w2otw7.streamlit.app/",
      },
    },
    {
      id: "dostii-ai-campaign",
      name: "Dostii AI Video Ad Campaign",
      subtitle: "AI-Generated Video Advertisement Campaign (100% Free Tools)",
      period: "Feb 2025 — Present",
      stack: [
        "Groq LLaMA 3.3",
        "Pika Labs",
        "ElevenLabs",
        "Suno AI",
        "InShot",
        "HTML/CSS/JS",
      ],
      highlights: [
        "Built complete 35-second Hindi video ad campaign targeting Long-Haul Truck Drivers using 100% FREE AI tools — Groq (script), Pika Labs (video), ElevenLabs (voiceover), Suno AI (music).",
        "Developed Groq-powered web app for auto-generating Hindi ad scripts and video prompts; persona research & A/B testing matrix for CAC optimization (₹20-₹40 per install).",
        "Engineered 4-scene video structure (Hook → Pain → Solution → CTA) with hyper-specific targeting (NH-44 highway drivers, 9 PM–2 AM, Moj/Josh platforms).",
        "Campaign strategy includes 6-second bumper ads, night-only targeting, and Haryanvi folk music variations — projected CTR 2–4%, Install Rate 15–25%, Day 1 Retention 40%+.",
      ],
      tags: ["AI"],
      accent: "rose",
      links: {
        code: "https://github.com/AshishChaubey2003/Dostii",
        live: "#",
      },
    },
    {
      id: "quickcart",
      name: "QuickCart",
      subtitle: "E-Commerce Store with Razorpay Payment Integration",
      period: "Nov 2024 — Present",
      stack: [
        "Django",
        "SQLite",
        "Razorpay Checkout",
        "Django Sessions",
        "Bootstrap 5",
        "JavaScript",
      ],
      highlights: [
        "Single-page e-commerce with product listing, quantity selector and live total calculation using Django + Razorpay Checkout API.",
        "4-layer double-payment prevention: frontend button disable, UUID idempotency key, select_for_update() DB lock and status-based order validation.",
        "Razorpay webhook for reliable server-side order confirmation with HMAC-SHA256 signature verification; session-based order tracking without login.",
      ],
      tags: ["Full Stack", "Backend"],
      accent: "amber",
      links: {
        code: "https://github.com/AshishChaubey2003/viprashop",
        live: "#",
      },
    },
    {
      id: "study-tracker",
      name: "Study Tracker API",
      subtitle: "High-Performance REST API with JWT Auth & Swagger Docs",
      period: "Apr 2025",
      stack: [
        "FastAPI",
        "SQLAlchemy",
        "SQLite",
        "JWT",
        "Pydantic v2",
        "Uvicorn",
      ],
      highlights: [
        "High-performance async REST API with OAuth2 JWT auth, full CRUD operations and auto-generated Swagger UI documentation.",
        "Clean architecture with Pydantic v2 strict validation for request/response schemas; async request handling via Uvicorn ASGI server.",
        "15-day streak tracking algorithm returning On-Track / Off-Track status; supports concurrent users with SQLAlchemy connection pooling.",
      ],
      tags: ["Backend"],
      accent: "rose",
      links: {
        code: "#",
        live: "#",
      },
    },
  ],

  education: [
    {
      school: "Shri Ramswaroop Memorial University",
      degree: "B.Tech — Computer Science",
      location: "Barabanki, Lucknow",
      period: "2021 — 2025",
      score: "CGPA 7.0 / 10",
    },
    {
      school: "Maharaji Devi Smarak Inter College",
      degree: "Class XII — PCM",
      location: "Ballia, Uttar Pradesh",
      period: "2020 — 2021",
      score: "65%",
    },
    {
      school: "Manasthali Education Center",
      degree: "Class X — PCM",
      location: "Ballia, Uttar Pradesh",
      period: "2017-2018",
      score: "51%",
    },
  ],

  certifications: [
    {
      title: "AWS Cloud Practitioner Essentials",
      issuer: "Coursera",
      year: "2024",
    },
    {
      title: "AI & Analytics Foundation",
      issuer: "IIT Hyderabad",
      year: "2024",
    },
  ],
};
